const Action = {
	ADD_ITEM: 'ADD_ITEM',
	UPDATE_PREPARED_ADD_ITEM: 'UPDATE_PREPARED_ADD_ITEM',
	
	POP_ITEM: 'POP_ITEM',
	UPDATE_PREPARED_POP_ITEM: 'UPDATE_PREPARED_POP_ITEM',
}

export default Action;